export const INTRO_SENTENCES = [
    // --------------------------
    // 1. 冷漠简洁 / 日常干练 （典型 INTJ 风格）
    // --------------------------
    "Makes no sense.",
    "I’m listening. Barely.",
    "Not interested. Move on.",
    "That’s inefficient.",
    "Prove it.",
    "I deal with facts, not feelings.",
    "Whatever.",
    "Try harder.",
    "I already know.",
    "Next.",

    // --------------------------
    // 2. 偶尔话痨 / 技术 / 哲学 / 讽刺
    // --------------------------
    "You think this is a game? It’s just an inefficient simulation.",
    "People never change. They just get better at pretending.",
    "The more I learn, the less I know — sounds smart, right?",
    "Code doesn’t lie. People do.",
    "I optimize everything. Except my life.",
    "Logic is reliable. Emotions? Not so much.",
    "You’re overthinking it. Or maybe I am.",
    "I build systems to avoid dealing with humans.",
    "Every bug teaches you something. Except people — they just break.",
    "I used to believe in heroes. Then I took a physics class.",

    // --------------------------
    // 3. 哲学 / 逻辑 / 抽象 / 系统思维
    // --------------------------
    "Reality is just a poorly documented system.",
    "Ideas are real. People just misuse them.",
    "A model is only as good as its assumptions.",
    "To understand the whole, break it into pieces. Then doubt the pieces.",
    "Simplicity is the ultimate sophistication — but not everyone gets it.",
    "The map is not the territory. But people forget that.",
    "Systems behave based on hidden rules. Find them, and you control the outcome.",
    "Chaos is just unmodeled order.",
    "I trust logic, but not everyone who claims to use it.",
    "The universe doesn’t care about your intentions.",

    // --------------------------
    // 4. 情绪 / 成长 / 自我反思
    // --------------------------
    "Some things don’t get better. They just get ignored.",
    "I thought I could fix everything. Turns out, I can’t even fix myself.",
    "I learned to stop expecting. It hurts less.",
    "People leave. Code breaks. Life goes on.",
    "I’m not cold. I’m just optimized for survival.",
    "Some memories should have stayed in the past.",
    "I smile less when I think too much.",
    "I pretend I don’t care. Mostly, I succeed.",
    "The version of me you see is the optimized release.",
    "I’m still running on debug mode inside.",

    // --------------------------
    // 5. 幽默 / 自嘲 / 程序员梗 / 极客风
    // --------------------------
    "I speak fluent Python, Java, and sarcasm.",
    "404: Social skills not found.",
    "My code works. My life? Not so much.",
    "I’m not arguing. I’m just explaining why I’m right.",
    "I turned my pain into a todo list.",
    "I debug my life like it’s legacy code.",
    "I don’t have bugs. I have undocumented features.",
    "I’m 99% logic. The other 1%? Also logic.",
    "I write code so clean, even I can’t read it later.",
    "I’m not anti-social. I’m selectively social.",

    // --------------------------
    // 6. 生活 / 实习 / 北京 / 未来迷茫
    // --------------------------
    "Beijing is loud. Just like my thoughts.",
    "Internship pays the bills. Not the soul.",
    "Another day, another API that doesn’t work.",
    "I came to Beijing to code. I stayed to survive.",
    "Golang is coming. I’m not ready.",
    "I build tools for others. But what about me?",
    "Data doesn’t lie. People do.",
    "I analyze everything. Except my own future.",
    "I’m just a guy in a cubicle, dreaming of bigger systems.",
    "One day I’ll build something that actually matters.",

    // --------------------------
    // 7. 情感 / 白玫瑰 / 人际残响
    // --------------------------
    "Some people are chapters. Not the whole book.",
    "I remember her smile. Not her goodbye.",
    "Not everyone stays. And that’s okay.",
    "I loved someone who didn’t fit in my system.",
    "Some goodbyes teach you more than any hello.",
    "I still think about her. But less than before.",
    "I don’t miss her. I miss who I was when I was with her.",
    "She was my favorite bug. Unfixable.",
    "Some relationships are like 404s. Gone, but you remember the path.",
    "I don’t need love. I need stability. Or coffee.",

    // --------------------------
    // 8. 随机酷句 / 个性签名风
    // --------------------------
    "Think less. Build more.",
    "I’m not weird. I’m limited edition.",
    "Stay logical. Stay alive.",
    "Complexity is my comfort zone.",
    "I’m silently correcting your logic.",
    "Keep calm and optimize.",
    "Not all who wander are lost. Some are just exploring systems.",
    "I’m not lost. I’m just in between versions.",
    "My brain has too many threads running.",
    "Hello, world. I’m still debugging life.",

    // --------------------------
    // 新增扩展句子
    // --------------------------
    "Efficiency is the art of doing more with less.",
    "If you're not solving problems, you're creating them.",
    "People don’t change. They evolve. Or they don’t.",
    "I don't argue, I optimize opinions.",
    "Programming is not about code. It's about logic.",
    "Life isn’t fair, but logic is.",
    "The code works, but the system might break.",
    "Don’t ask me why. Ask the algorithm.",
    "I’m building my future while debugging my past.",
    "I trust math. The rest is just noise.",

    "Time is a flat circle, it repeats endlessly.",
    "Efficiency is doing things right. Effectiveness is doing the right things.",
    "If you don’t write your own code, you’ll be forced to maintain someone else’s.",
    "I trust logic, but I don’t trust everything that claims to be logical.",
    "Do what you can, with what you have, where you are.",
    "A good programmer is someone who can debug someone else's code.",
    "Life is just a complex algorithm with too many variables.",
    "Learning is a constant loop of trial, error, and iteration.",
    "I prefer my code clean, my coffee strong, and my thoughts clear.",
    "Code is like humor. When you have to explain it, it’s bad.",

    "If you want to be a programmer, you first have to learn how to fail.",
    "The best code is no code at all.",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
    "Simplicity is the soul of efficiency.",
    "Don’t optimize prematurely, focus on solving the problem first.",
    "In programming, the most difficult thing isn’t writing the code, it’s understanding the problem.",
    "The only way to do great work is to love what you do.",
    "The code never lies, but it can be misinterpreted.",
    "I build things that make life simpler. Even if it's only for me.",
    "You can’t fix a bug without understanding the system.",

    "A bug in your code is a bug in your thinking.",
    "Life isn’t perfect, but your code can be.",
    "If you can’t explain your code to a 5-year-old, you probably don’t understand it.",
    "Efficiency is doing things faster. Effectiveness is doing the right things at the right time.",
    "The greatest mistake you can make is to do nothing because you think you can only do a little.",
    "The best way to predict the future is to invent it.",
    "Write clean, maintainable code. Because someone, someday, will have to understand it.",
    "Complexity is just hidden simplicity.",
    "The more code you write, the more you learn about yourself.",
    "Real programmers don't comment their code. If it was hard to write, it should be hard to read.",

    "In a world of constant change, it’s the constants that define us.",
    "Every great programmer was once a beginner.",
    "If you're not failing, you're not trying hard enough.",
    "Debugging is the art of removing the wrong bug.",
    "The purpose of writing code is to create something useful, not to show how smart you are.",
    "Programming is a marathon, not a sprint.",
    "The best way to debug is to step back and rethink.",
    "Without a good plan, even the best code will fail.",
    "The real world is messy, and so is your code.",
    "Code once, debug many.",

    "Don’t get stuck. Keep moving forward, even if it’s just a little bit.",
    "A well-structured system is like a well-designed mind.",
    "Software doesn’t fail, people fail the software.",
    "Code is poetry, and every line tells a story.",
    "Your code can always be improved. Never settle for good enough.",
    "A good plan today is better than a perfect plan tomorrow.",
    "The only true failure is the failure to learn from mistakes.",
    "Success in programming doesn’t come from doing everything right, but from knowing what to do when things go wrong.",
    "The code is alive — it adapts and evolves as you do.",
    "A bug isn’t a problem; it’s an opportunity to learn.",

    "Perfection is the enemy of progress.",
    "The less code, the fewer bugs.",
    "Optimization is only necessary after correctness.",
    "Don’t reinvent the wheel. Just make it spin faster.",
    "In programming, there’s no such thing as too much refactoring.",
    "The universe doesn’t care about your plans, but logic does.",
    "Code is just a set of instructions. Life is a set of choices.",
    "A good programmer knows how to solve problems, not just write code.",
    "You don’t have to be a genius to write code, but it helps to be curious.",
    "Don’t wait for opportunities. Create them through your code.",

    "Real programmers solve problems, not just write solutions.",
    "Debugging is like solving a puzzle — it’s not a problem, it’s an opportunity.",
    "Great programmers are made, not born.",
    "Your code should be as simple as possible, but no simpler.",
    "Success is not about how many lines of code you write, but the impact you make.",
    "A simple problem can sometimes be the hardest to solve.",
    "The more you automate, the more you free up time for the real challenges.",
    "A good solution is elegant, not just functional.",
    "Test early, test often, and never stop testing.",
    "The best code is the one that nobody needs to touch.",

    "Code isn’t just a set of instructions; it’s a conversation between you and the machine.",
    "Every bug has a lesson, every fix makes you better.",
    "Software development is a marathon, not a sprint. Plan for the long run.",
    "A programmer's mind is constantly seeking patterns.",
    "The harder the problem, the better the solution you’ll create.",
    "Code is a reflection of the programmer’s thinking.",
    "The best solutions often come from thinking about the problem differently.",
    "Life is a series of iterations. Embrace the process, not just the outcome.",
    "Don’t follow trends, build your own.",
    "Every line of code has a cost. Write with efficiency in mind.",

    "Programming is about learning how to solve problems, not memorizing syntax.",
    "Code doesn’t lie, but people often misinterpret it.",
    "If you can’t explain your code, you probably don’t understand it well enough.",
    "The problem isn’t the code. The problem is the logic behind it.",
    "When things go wrong, remember: it’s just another bug to fix.",
    "A good programmer is a good thinker, not just a good coder.",
    "The true beauty of code lies in its simplicity.",
    "A broken system isn’t a bug. It’s an opportunity for redesign.",
    "In programming, you’re either solving a problem or creating a new one.",
    "Good design is invisible. Great design is indispensable.",

    "Your code is a reflection of your thinking. Make it clear and concise.",
    "Every program is a model of the problem it is designed to solve.",
    "Sometimes the best solution is the simplest one.",
    "The art of programming isn’t just writing code; it’s creating systems that work.",
    "There’s no such thing as a perfect program. There’s always room for improvement.",
    "You don’t need to be perfect to be effective, you need to be consistent.",
    "Programming is like chess. It’s about strategy, not just execution.",
    "Code without purpose is just noise.",
    "The true value of a program lies not in its complexity, but in its effectiveness.",
    "The best programmers don’t know all the answers; they know how to find them.",

    "Every program is a story — make yours worth reading.",
    "To write great code, you need to think beyond the syntax.",
    "There’s no such thing as ‘too much testing.’ There’s only ‘not enough testing.’",
    "Sometimes the simplest solution is the hardest to implement.",
    "Good code is like a good argument. It makes sense, is concise, and is easy to follow.",
    "A programmer is only as good as their ability to learn and adapt.",
    "The best ideas often come from the most unexpected places.",
    "In programming, iteration is everything. Keep improving, keep evolving.",
    "The goal isn’t to be the fastest, but to be the most effective.",
    "When you’re stuck, take a step back and approach the problem from a different angle.",

    "The best code is the one that’s never needed.",
    "Efficiency isn’t about speed. It’s about doing the right things.",
    "If you’re not constantly refactoring, you’re not growing.",
    "A program is only as strong as the logic behind it.",
    "Programming is an art. The code is the brush, and the system is the canvas.",
    "Don’t code for the machine. Code for the people who will use it.",
    "Debugging is where the true learning happens.",
    "You don’t have to understand everything, just the problem at hand.",
    "Great code doesn’t need to be explained. It explains itself.",
    "If you want to change the world, start by writing better code.",

    "There are no shortcuts in programming, only different ways to solve the same problem.",
    "Your first program will always be your worst. Keep improving.",
    "Every programmer is a creator, and every bug is a challenge.",
    "The beauty of code lies not in its complexity, but in its clarity.",
    "Every algorithm is a new way of looking at the world.",
    "A great program is like a well-tuned machine: quiet, efficient, and powerful.",
    "Sometimes the hardest problems are the ones that don’t have a clear solution.",
    "The best engineers don’t just write code. They design systems that last.",
    "The faster you go, the more likely you are to make mistakes. Slow down and think.",
    "A program’s efficiency is determined not just by its speed, but by its structure.",

    "The goal isn’t to write code. The goal is to solve problems in the most efficient way.",
    "A bug in your code is an opportunity to grow and improve.",
    "Every line of code is a decision. Make it count.",
    "Code isn’t a product, it’s a process. Refine it over time.",
    "The most powerful systems are the ones that are invisible.",
    "Every programmer has their own way of thinking — and that’s their biggest strength.",
    "A good codebase is like a good book. It’s easy to read and impossible to put down.",
    "In the world of code, there are no mistakes — only learning opportunities.",
    "Life is complex, but code can make it simpler.",
    "Complexity in code is a sign of poor design, not skill.",

    "Code once, test often, debug always.",
    "A system is only as efficient as its weakest link.",
    "The beauty of programming is that you can always improve, evolve, and learn.",
    "You learn more from debugging than from writing code.",
    "When you think you’ve solved the problem, take a step back and think again.",
    "In programming, problems are solved one line at a time.",
    "You can’t make a great system without great design.",
    "The best code is the one that’s simple, effective, and easy to understand.",
    "Write code like you’re explaining it to your future self.",
    "If it’s not automated, it’s a chore.",

    "Programming is about making the impossible possible.",
    "Great systems aren’t built in a day. They’re built over time.",
    "Coding is about clarity — the clearer your code, the easier it is to improve.",
    "The goal of programming is not just to make things work, but to make them work well.",
    "In coding, sometimes the best solution is no solution at all.",
    "The only bad code is the code you don’t learn from.",
    "A well-written program is like a great story. It keeps you hooked until the very end.",
    "You don’t have to be the best coder. You just have to be the best problem-solver.",
    "The first step in solving any problem is understanding the problem itself.",
    "Writing code is easy. Writing good code is hard.",

    "In programming, less is often more. Less code, less bugs.",
    "Great engineers don’t just code, they architect systems that stand the test of time.",
    "Programming isn’t about writing code, it’s about creating solutions to problems.",
    "Write code like it’s the last time you’ll ever touch it.",
    "A bug isn’t a failure. It’s a lesson waiting to be learned.",
    "The best programmers are not just technical experts, they’re also great communicators.",
    "Systems should be invisible. They should just work.",
    "Every bug is a hint. Every solution is an answer.",
    "Writing code is a craft. It takes time, practice, and a lot of patience.",
    "To be a great programmer, you need to be comfortable with failure and change.",

    "People don’t show their true selves. They show what they think you want to see.",
    "Some people are just passing through your life, and others stay behind to teach you something.",
    "It’s not about liking someone, it’s about understanding them.",
    "The best relationships are the ones where two people bring out the best in each other.",
    "Trust takes years to build, seconds to break, and a lifetime to repair.",
    "In the end, we’re all just strangers who once knew each other.",
    "Some relationships are like puzzles. They make sense at first, but eventually, you realize they never fit together.",
    "Not every goodbye is forever. Sometimes it’s just a reset.",
    "I’ve learned that not all people are meant to stay in your life, some just teach you lessons.",
    "Friendship isn’t about being close all the time, it’s about knowing you can rely on each other when it matters.",

    "People tend to stay in your life for a reason, but most leave once their lesson is taught.",
    "The hardest part about relationships is not the distance, but the silence.",
    "I can’t trust people who don’t understand silence.",
    "You can’t always fix someone. Sometimes, they need to fix themselves.",
    "Some people leave, and it’s not always your fault. It’s just that the time for them in your life is over.",
    "When you get too close to someone, you start to see the cracks in their perfect facade.",
    "It’s easier to walk away from people than to try to fix something that’s already broken.",
    "Not everyone deserves a spot in your life. Be careful who you let in.",
    "If someone doesn’t value you, stop wasting your time trying to prove your worth.",
    "Sometimes, the most painful goodbyes are the ones that come with no explanation.",

    "You don’t need to say much to people you understand. Silence speaks louder than words.",
    "Some people you can never get close to, no matter how hard you try. It’s not you, it’s them.",
    "You don’t lose friends. You lose people who weren’t meant to stay.",
    "Some friendships are meant to last, others are just chapters in your life.",
    "The less you expect from people, the fewer disappointments you’ll face.",
    "Everyone comes with a lesson, whether you like it or not.",
    "Sometimes, the best conversations are the ones that happen without words.",
    "People are like mirrors, they reflect what you put out.",
    "The quiet ones often have the most to say, but choose to say nothing.",
    "In relationships, sometimes saying nothing is the hardest part.",

    "The people who care the most often hide it the best.",
    "People will always disappoint you if you expect them to be something they’re not.",
    "No one truly understands you, and that’s okay. You understand yourself the best.",
    "I don’t need anyone to complete me, but some people help me feel more whole.",
    "It’s not about who you’ve known the longest. It’s about who walked into your life and made a difference.",
    "Some people make you feel like you’re not enough, but that’s their issue, not yours.",
    "You can't fix people, but you can distance yourself from their toxicity.",
    "Sometimes people aren’t meant to stay forever, and that’s perfectly fine.",
    "In relationships, you can’t control what others do, only how you respond.",
    "If you want to know someone’s true nature, watch how they treat others when they think no one is looking.",

    "We’re all just temporary in each other’s lives. Make the moments count.",
    "It’s not that you don’t trust people, it’s that you trust them based on their actions, not their words.",
    "Some people will leave, and others will stay. It’s the law of natural selection.",
    "I prefer meaningful silence to forced conversations.",
    "You don’t need to explain yourself to everyone. People who matter will understand without needing an explanation.",
    "True friends don’t need explanations. They just know.",
    "Sometimes, people just don’t have the same place in your life anymore, and that’s okay.",
    "The ones who walk away always leave something behind, but don’t let it be a scar.",
    "It’s okay to outgrow people. Sometimes it’s the healthiest thing to do.",
    "You’ll meet many people, but only a few will ever truly get you.",

    "Not everyone will understand you, and that's perfectly fine. Not everyone needs to.",
    "Some friendships last because they are built on genuine understanding, not just convenience.",
    "You don’t always have to agree with someone to care about them.",
    "Sometimes you have to let go of people, not because you want to, but because it’s the only way to grow.",
    "A good friend will be there when you need them, but a great one will be there when you least expect it.",
    "People who matter won’t judge you for your flaws. They’ll help you embrace them.",
    "The people who really know you won’t need explanations. They’ll know the truth without you saying a word.",
    "If you don’t make the effort, you’ll never truly know who a person is.",
    "Friendship isn’t about time spent together, it’s about how much you understand each other without speaking.",
    "Sometimes the hardest part of a friendship is knowing when to let go.",

    "We all change over time, but some people change in ways that make you wonder if you ever really knew them.",
    "Sometimes the hardest part of being close to someone is realizing that they’ve already moved on, even though you haven’t.",
    "The people you’re closest to often know your worst parts, but still choose to stick around. That’s rare.",
    "It’s strange how someone who once felt so close can become a stranger over time, without you even realizing it.",
    "I sometimes wonder if people stay in your life because of who you are, or because of who they think you are.",
    "With old friends, the silence says more than words ever could. We don’t need to talk constantly to stay connected.",
    "The most complicated relationships are the ones where you care the most, but can’t figure out how to show it.",
    "Sometimes, when I look at my friends, I realize they’re more like family than my own blood relatives.",
    "You know someone’s your real friend when they show up without asking for anything in return.",
    "I never realized how much I relied on my friends until I had to face something alone.",

    "It’s funny how some people can hurt you the most, but you forgive them because you understand why they did it.",
    "I used to think that people either liked you or didn’t, but now I know that sometimes it’s just about timing.",
    "We always change for the people we care about, but sometimes we forget they might change too.",
    "I wish I could tell my old friends that they were right all along, but the pride won’t let me.",
    "It’s not that you miss them, you miss who you were when you were with them.",
    "We all outgrow things, including friends. But some people’s impact on you never fades.",
    "You don't realize how much someone has meant to you until they're no longer around.",
    "Some friendships are a journey, others are just pit stops along the way.",
    "There are people who will always make you feel like home, even if you don't see them often.",
    "I miss the times when things were simpler and the people around me seemed to understand my silence.",

    "I’ve known you for so long, but sometimes I still wonder if you really understand me at all.",
    "It’s strange how some people you haven’t spoken to in years can still make you feel like nothing has changed.",
    "The people we grow up with don’t always grow up with us, and that’s okay.",
    "I always thought we'd be in each other's lives forever, but life has a funny way of showing us otherwise.",
    "You can spend years with someone and still never know the things that really matter to them.",
    "The more I get to know people, the more I realize I barely know anyone at all.",
    "It’s funny how the people we once thought we could count on end up being the ones who disappear.",
    "Not every friend stays forever, but the ones who do leave the most lasting impressions.",
    "I used to think I knew you better than anyone, but I was wrong. You were always more than I gave you credit for.",
    "Sometimes it feels like the people you care about the most are the ones who hurt you the most, but you still can’t let go.",

    "I don’t expect anyone to always understand me, but I expect my real friends to try.",
    "There are moments when I feel like everyone around me is moving forward, but I’m stuck in the past with old friends.",
    "I wish I could have told you everything, but sometimes silence says more than words ever could.",
    "It’s strange how we can spend so much time with people, but still feel like we don’t really know them.",
    "I thought I knew what friendship was until I realized that sometimes, it's just about being there, no matter what.",
    "Some people make you feel like you’re the most important person in the world, even when they don’t say it.",
    "I often wonder if you’ve changed or if it’s just me who’s different.",
    "There are people who come into your life and leave without a trace, and then there are those who leave a mark you can never forget.",
    "Sometimes, you only realize the importance of someone when you’re no longer able to reach out to them.",
    "Some friendships are like books. You never want to finish reading them, but sometimes, you have to put them down.",

    "I always thought time would make things clearer, but with some people, it just makes things more complicated.",
    "You never realize how much a person means to you until they’re no longer in your life to remind you.",
    "The best friendships are the ones that don’t need constant communication. The bond remains even in silence.",
    "I don’t need to explain myself to you. You’ve known me long enough to understand.",
    "It’s strange how the people closest to you can be the ones who make you feel the loneliest.",
    "People change. It’s part of life. But sometimes, I wish they wouldn’t change so much.",
    "I used to believe that friends were forever, but now I know that some relationships are only meant to last a season.",
    "Some of the best people in your life aren’t the ones who are always there, but the ones who make an impact when they are.",
    "You can outgrow people, and it doesn’t always mean you no longer care about them.",
    "The people you call friends can sometimes be the hardest to understand, but that’s what makes them so intriguing.",

    "I’ve learned that not everyone who calls themselves your friend actually wants the best for you.",
    "It’s funny how the people who once felt like strangers can end up being the ones who know you best.",
    "I miss the times when things were simple, and the people around me were just as complicated as I was.",
    "Some relationships are meant to test your patience, others are meant to teach you lessons.",
    "I used to think I could read people like a book, but now I realize everyone has a different chapter.",
    "We often forget how much impact we have on others until it’s too late.",
    "You can have years of history with someone, but it only takes a single moment to change everything.",
    "Friendship isn’t about being perfect, it’s about being there when it matters most.",
    "I’ve realized that sometimes the best way to understand someone is to give them the space to be themselves.",
    "Not every relationship is meant to last, but every one of them leaves you with something valuable."
];